version: '3'
services:
  umami:
    image: ghcr.io/mikecao/umami:postgresql-latest
    ports:
      - "3006:3000"
    environment:
      DATABASE_URL: postgresql://umami:umami@db:5432/umami # Change password
      DATABASE_TYPE: postgresql
      HASH_SALT: '' # Add random string
    depends_on:
      - db
  db:
    image: postgres:12-alpine
    environment:
      POSTGRES_DB: umami
      POSTGRES_USER: umami
      POSTGRES_PASSWORD: umami # example password
    volumes:
      - ./sql/schema.postgresql.sql:/docker-entrypoint-initdb.d/schema.postgresql.sql:ro
      - ./data:/var/lib/postgresql/data
