version: '3'
services:
  app:
    image: 'jc21/nginx-proxy-manager:latest'
    container_name: NginxProxyManager
    restart: unless-stopped
    depends_on:
      proxy-db:
        condition: service_healthy
    ports: # Don't change
      - '80:80'
      - '81:81'
      - '443:443'
    volumes:
      - /services/NginxProxyManager/app/config.json:/app/config/production.json
      - /services/NginxProxyManager/app/data:/data
      - /services/NginxProxyManager/app/letsencrypt:/etc/letsencrypt
    healthcheck:
      test: ["CMD", "curl", "-fk", "http://127.0.0.1:81"]
      interval: 30s
      timeout: 10s
      retries: 6

  proxy-db:
    image: tobi312/rpi-mariadb:10.3
    container_name: NginxProxyManager-DB
    restart: unless-stopped
    volumes:
      - /services/NginxProxyManager/db/data:/var/lib/mysql
    environment:
      TZ: Africa/Johannesburg
      MYSQL_ROOT_PASSWORD: '' # Add root password
      MYSQL_DATABASE: 'npm'
      MYSQL_USER: 'nginx'
      MYSQL_PASSWORD: '' # Add user password
    ports:
      - 3306:3306
    healthcheck:
      test:  mysqladmin ping -h 127.0.0.1 -u root --password=$$MYSQL_ROOT_PASSWORD || exit 1
      interval: 30s
      timeout: 5s
      retries: 5
