version: '3'

services:
  traefik:
    container_name: Traefik-reverse-proxy
    image: traefik:v2.3
    command: --api.insecure=true --providers.docker
    ports:
      - 80:80
      - 443:443
      - 1883:1883
      - 8080:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock


######################################################################


  app:
    image: organizr/organizr  
    container_name: organizr-dashboard
    networks:
      organizr_network:
        ipv4_address: 172.12.0.2
    volumes:
      - /services/organizr/app/config:/config
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
    restart: unless-stopped
    env_file:
      - ../../Selfhosted-config/Dashboard/Organizr.env
    healthcheck:
      test: ["CMD", "curl", "-fk", "http://<domain>:280"]
      interval: 30s
      timeout: 10s
      retries: 6
      

######################################################################


  nextcloud-web:
    image: nginx:stable-alpine    
    container_name: nextcloud-proxy
    networks:
      nextcloud_network:
        ipv4_address: 172.10.0.2
    ports:
      - 80:80
      - 443:443
    volumes:
      - /services/nextcloud/proxy/certs:/root/ssl/nextcloud:ro
      - ./proxy/nginx.conf:/etc/nginx/conf.d/default.conf
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-fk", "https://<domain>:443"]
      interval: 30s
      timeout: 10s
      retries: 6

  db:
    image: mariadb
    container_name: nextcloud-mariadb
    networks:
      nextcloud_network:
        ipv4_address: 172.10.0.3
    volumes:
      - /services/nextcloud/db:/var/lib/mysql:rw
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - ../../Selfhosted-config/Cloud/mariaDB.env
    restart: unless-stopped

  app:
    image: nextcloud:latest
    container_name: nextcloud-app
    networks:
      nextcloud_network:
        ipv4_address: 172.10.0.4
    depends_on:
      - proxy
      - db
    volumes:
      - /services/nextcloud/app/www:/var/www/html:rw
      - /mnt/zfspool/nextcloud:/var/www/html/data:rw
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - ../../Selfhosted-config/Cloud/Nextcloud.env
    restart: unless-stopped      
  
  onlyoffice:
    image: onlyoffice/documentserver
    container_name: nextcloud-documentserver
    networks:
      nextcloud_network:
        ipv4_address: 172.10.0.5
    ports:
      - 880:80
      - 8000:8000
      - 8080:8080
      - 8443:443
    healthcheck:
      test: ["CMD", "curl", "-fk", "https://<domain>:8443"]
      interval: 30s
      timeout: 10s
      retries: 6
    volumes:
      - /services/nextcloud/DocumentServer/logs:/var/log/onlyoffice:rw
      - /services/nextcloud/DocumentServer/data:/var/www/onlyoffice/Data:rw
      - /services/nextcloud/DocumentServer/lib:/var/lib/onlyoffice:rw
      - /services/nextcloud/DocumentServer/db:/var/lib/postgresql:rw
    restart: unless-stopped
    env_file:
      - ../../Selfhosted-config/Cloud/Onlyoffice.env


######################################################################


  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin-media-server
    user: 1000:1000
    network_mode: "host"
    restart: "unless-stopped"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://cloudk.ddns.net:8096"]
      interval: 30s
      timeout: 10s
      retries: 6
    env_file:
      - ../../Selfhosted-config/Media/Jellyfin.env
    volumes:
      - /services/Jellyfin/config:/config
      - jellyfin-cache:/cache
      - /mnt/zfspool/nextcloud/jellyfin/files/Media:/media


######################################################################


  openhab:
    image: openhab/openhab
    container_name: openhab-server
    restart: unless-stopped
    networks:
      openhab_network:
        ipv4_address: 172.16.5.2
    ports:
      - 3080:80
      - 3443:443
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /services/openhab/addons:/openhab/addons:rw
      - /services/openhab/config:/openhab/conf:rw
      - /services/openhab/userdata:/openhab/userdata:rw
    env_file:
      - ../../Selfhosted-config/Openhab/Openhab.env
    healthcheck:
      test: ["CMD", "curl", "-fk", "http://<domain>:3080"]
      interval: 30s
      timeout: 10s  
      retries: 6
  
  MQTT-broker:
    image: eclipse-mosquitto
    container_name: openhab-mosquitto-broker
    restart: unless-stopped
    networks:
      openhab_network:
        ipv4_address: 172.16.5.3
    ports:
      - 1883:1883
    volumes:
      - /services/mosquitto/config:/mosquitto/config:rw
      - /services/mosquitto/data:/mosquitto/data:rw
      - /services/mosquitto/logs:/mosquitto/logs:rw
    healthcheck:
      test: ["CMD", "curl", "-fk", "http://<domain>:1883"]
      interval: 30s
      timeout: 10s
      retries: 6



networks:
  organizr_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.12.0.0/16
          gateway: 172.12.0.1

networks:
  nextcloud_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.10.0.0/16
          gateway: 172.10.0.1

networks:
  openhab_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.5.0/16
          gateway: 172.16.5.1

volumes:
  jellyfin-cache:
    driver: local
