##### Nextcloud Stack #####
#  proxy - nginxProxyManager(separate)
#  db - mariaDB
#  app - nextcloud
#  doc server - onlyoffice
#  By Benricok
###########################

version: '3'  

services:
  db:
    image: mariadb
    container_name: nextcloud-mariadb
    ports:
      - 801:80
    networks:
      nextcloud_network:
        ipv4_address: 172.10.0.3
    volumes:
      - /services/nextcloud/db:/var/lib/mysql:rw
      - /etc/localtime:/etc/localtime:ro
    environment:
      - MYSQL_ROOT_PASSWORD= # Add root password  
      - MYSQL_PASSWORD= # Add user password
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
    restart: unless-stopped
    healthcheck:
      test:  mysqladmin ping -h 127.0.0.1 -u root --password=$$MYSQL_ROOT_PASSWORD || exit 1
      interval: 30s
      timeout: 5s
      retries: 5

  app:
    image: nextcloud:latest
    container_name: nextcloud-app
    networks:
      nextcloud_network:
        ipv4_address: 172.10.0.4
    depends_on:
      - db
    volumes:
      - /services/nextcloud/app/www:/var/www/html:rw
      - /mnt/zfspool/nextcloud:/var/www/html/data:rw
      - /etc/localtime:/etc/localtime:ro
    environment:
      - VIRTUAL_HOST= # Add domain
    restart: unless-stopped      
    healthcheck:
      test: ["CMD", "curl", "-fk", "https://nc.<domain>"] # Add domain
      interval: 30s
      timeout: 10s
      retries: 6
  
  onlyoffice:
    image: onlyoffice/documentserver
    container_name: nextcloud-documentserver
    networks:
      nextcloud_network:
        ipv4_address: 172.10.0.5
    ports:
      - 880:80
      - 8000:8000
      - 8080:8080
      - 8443:443
    healthcheck:
      test: ["CMD", "curl", "-fk", "https://doc.<domain>"] # Add domain
      interval: 30s
      timeout: 10s
      retries: 6
    volumes:
      - /services/nextcloud/DocumentServer/logs:/var/log/onlyoffice:rw
      - /services/nextcloud/DocumentServer/data:/var/www/onlyoffice/Data:rw
      - /services/nextcloud/DocumentServer/lib:/var/lib/onlyoffice:rw
      - /services/nextcloud/DocumentServer/db:/var/lib/postgresql:rw
    restart: unless-stopped
    environment:
      - USE_UNAUTHORIZED_STORAGE=false

networks:
  nextcloud_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.10.0.0/16
          gateway: 172.10.0.1
