##### Nextcloud Stack #####
#  proxy - nginx
#  db - mariaDB
#  app - nextcloud
#  doc server - onlyoffice
#  By Benricok
###########################

version: '3'  

services:

  proxy:
    image: nginx:stable-alpine    
    container_name: nextcloud-proxy
    networks:
      nextcloud_network:
        ipv4_address: 172.10.0.2
    ports:
      - 80:80
      - 443:443
      - 800:800
      - 2433:2443
    volumes:
      - /services/nextcloud/proxy/certs:/root/ssl/nextcloud:ro
      - ./proxy/nginx.conf:/etc/nginx/conf.d/default.conf
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-fk", "https://<domain>:443"]
      interval: 30s
      timeout: 10s
      retries: 6:w

  db:
    image: mariadb
    container_name: nextcloud-mariadb
    networks:
      nextcloud_network:
        ipv4_address: 172.10.0.3
    volumes:
      - /services/nextcloud/db:/var/lib/mysql:rw
      - /etc/localtime:/etc/localtime:ro
    environment:
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_PASSWORD=
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
    restart: unless-stopped

  app:
    image: nextcloud:latest
    container_name: nextcloud-app
    networks:
      nextcloud_network:
        ipv4_address: 172.10.0.4
    depends_on:
      - proxy
      - db
    volumes:
      - /services/nextcloud/app/www:/var/www/html:rw
      - /mnt/zfspool/nextcloud:/var/www/html/data:rw
      - /etc/localtime:/etc/localtime:ro
    environment:
      - VIRTUAL_HOST=<domain>
    restart: unless-stopped      
  
  onlyoffice:
    image: onlyoffice/documentserver
    container_name: nextcloud-documentserver
    networks:
      nextcloud_network:
        ipv4_address: 172.10.0.5
    ports:
      - '880:80'
      - '8000:8000'
      - '8080:8080'
      - '8443:443'
    healthcheck:
      test: ["CMD", "curl", "-fk", "https://<domain>:8443"]
      interval: 30s
      timeout: 10s
      retries: 6
    volumes:
      - /services/nextcloud/DocumentServer/logs:/var/log/onlyoffice:rw
      - /services/nextcloud/DocumentServer/data:/var/www/onlyoffice/Data:rw
      - /services/nextcloud/DocumentServer/lib:/var/lib/onlyoffice:rw
      - /services/nextcloud/DocumentServer/db:/var/lib/postgresql:rw
    restart: unless-stopped
    environment:
      - USE_UNAUTHORIZED_STORAGE=false

networks:
  nextcloud_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.10.0.0/16
          gateway: 172.10.0.1
