######## Nextcloud stack ########
## proxy - nginx
## certs - letsencrypt
## db    - mariaDB
## app   - nextcloud
## doc   - onlyoffice
#################################

version: '3'  

services:

  proxy:
    image: jwilder/nginx-proxy:alpine
    labels:
      - "com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy=true"
    container_name: nextcloud-proxy
    networks:
      - nextcloud_network
    ports:
      - 80:80
      - 443:443
    volumes:
      - /services/nextcloud/proxy/conf.d:/etc/nginx/conf.d:rw
      - /services/nextcloud/proxy/vhost.d:/etc/nginx/vhost.d:rw
      - /services/nextcloud/proxy/html:/usr/share/nginx/html:rw
      - /services/nextcloud/proxy/certs:/etc/nginx/certs:ro
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
    restart: unless-stopped

  letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: nextcloud-letsencrypt
    depends_on:
      - proxy
    networks:
      - nextcloud_network
    volumes:
      - /services/nextcloud/proxy/certs:/etc/nginx/certs:rw
      - /services/nextcloud/proxy/vhost.d:/etc/nginx/vhost.d:rw
      - /services/nextcloud/proxy/html:/usr/share/nginx/html:rw
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    restart: unless-stopped

  db:
    image: mariadb
    container_name: nextcloud-mariadb
    networks:
      - nextcloud_network
    volumes:
      - /services/nextcloud/db:/var/lib/mysql:rw
      - /etc/localtime:/etc/localtime:ro
    environment:
      - MYSQL_ROOT_PASSWORD=YOUR_PASSWORD   # Change Password
      - MYSQL_PASSWORD=YOURPASSWORD         # Change Password
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
    restart: unless-stopped

  app:
    image: nextcloud:latest
    container_name: nextcloud-app
    networks:
      - nextcloud_network
    depends_on:
      - letsencrypt
      - proxy
      - db
    volumes:
      - /services/nextcloud/app/www/html:/var/www/html:rw
      - /mnt/zfspool/nextcloud:/var/html/data:rw            # Change data directory
      - /etc/localtime:/etc/localtime:ro
    environment:
      - VIRTUAL_HOST=cloudk.ddns.net
      - LETSENCRYPT_HOST=cloudk.ddns.net
      - LETSENCRYPT_EMAIL=bfjkrog@pm.me
    restart: unless-stopped      
  
  onlyoffice:
    image: onlyoffice/documentserver
    container_name: nextcloud-documentserver
    networks:
      - nextcloud_network
    ports:
      - 800:80
      - 4333:433
    depends_on:
      - app
    volumes:
      - /services/nextcloud/DocumentServer/logs:/var/log/onlyoffice
      - /services/nextcloud/DocumentServer/data:/var/www/onlyoffice/Data
      - /services/nextcloud/DocumentServer/lib:/var/lib/onlyoffice
      - /services/nextcloud/DocumentServer/db:/var/lib/postgresql

networks:
  nextcloud_network:
