##### Nextcloud Stack #####
#  proxy - nginx
#  db - mariaDB
#  app - nextcloud
#  doc server - onlyoffice
#  By Benricok
###########################

version: '3'  

services:

  proxy:
    image: nginx:stable-alpine    
    container_name: nextcloud-proxy
    networks:
      nextcloud_network:
        - ipv4_address: 172.10.0.2
    ports:
      - 80:80
      - 443:443
      - 800:800
      - 2433:2443
    volumes:
      - /services/nextcloud/proxy/config:/etc/nginx/:rw
      - /services/nextcloud/proxy/certs:/root/ssl/nextcloud:ro
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
    restart: unless-stopped

  db:
    image: mariadb
    container_name: nextcloud-mariadb
    networks:
      nextcloud_network:
        - ipv4_address: 172.10.0.3
    volumes:
      - /services/nextcloud/db:/var/lib/mysql:rw
      - /etc/localtime:/etc/localtime:ro
    environment:
      - MYSQL_ROOT_PASSWORD=                                # Append Password
      - MYSQL_PASSWORD=                                     # Append Password
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
    restart: unless-stopped

  app:
    image: nextcloud:latest
    container_name: nextcloud-app
    networks:
      nextcloud_network:
         - ipv4_address: 172.10.0.4
    depends_on:
      - proxy
      - db
    volumes:
      - /services/nextcloud/app/www:/var/www/html:rw
      - /services/nextcloud/app/apache:/etc/apache2:rw
      - /mnt/zfspool/nextcloud:/var/www/html/data:rw          # Change to your data directory
      - /etc/localtime:/etc/localtime:ro
    environment:
      - VIRTUAL_HOST=                                         # Append your domain
    restart: unless-stopped      
  
  onlyoffice:
    image: onlyoffice/documentserver
    container_name: nextcloud-documentserver
    networks:
      nextcloud_network:
        - ipv4_address: 172.10.0.5
    depends_on:
      - proxy
      - app
    volumes:
      - /services/nextcloud/DocumentServer/logs:/var/log/onlyoffice:rw
      - /services/nextcloud/DocumentServer/data:/var/www/onlyoffice/Data:rw
      - /services/nextcloud/DocumentServer/lib:/var/lib/onlyoffice:rw
      - /services/nextcloud/DocumentServer/db:/var/lib/postgresql:rw

networks:
  nextcloud_network:
    driver: bridge
    ipam:
      config:
        - subnet 172.10.0.0/16
        - gateway 172.10.0.1
