version: '3'

services:
  openhab:
    image: openhab/openhab
    container_name: openhab-server
    restart: unless-stopped
    networks:
      openhab_network:
        ipv4_address: 172.16.5.2
    ports:
      - 3080:80
      - 3443:443
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /services/openhab/addons:/openhab/addons:rw
      - /services/openhab/config:/openhab/conf:rw
      - /services/openhab/userdata:/openhab/userdata:rw
    environment:
      OPENHAB_HTTP_PORT: "80"
      OPENHAB_HTTPS_PORT: "443"
      EXTRA_JAVA_OPTS: "-Duser.timezone=Africa/Johannesburg"
    healthcheck:
      test: ["CMD", "curl", "-fk", "http://<domain>:3080"]
      interval: 30s
      timeout: 10s  
      retries: 6
  
  MQTT-broker:
    image: eclipse-mosquitto
    container_name: openhab-mosquitto-broker
    restart: unless-stopped
    networks:
      openhab_network:
        ipv4_address: 172.16.5.3
    ports:
      - 1883:1883
    volumes:
      - /services/mosquitto/config:/mosquitto/config:rw
      - /services/mosquitto/data:/mosquitto/data:rw
      - /services/mosquitto/logs:/mosquitto/logs:rw
    healthcheck:
      test: ["CMD", "curl", "-fk", "http://<domain>:1883"]
      interval: 30s
      timeout: 10s
      retries: 6

networks:
  openhab_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.5.0/16
          gateway: 172.16.5.1
