version: '2.2'

services:
  openhab:
    image: openhab/openhab
    container_name: openhab-server
    restart: unless-stopped
    networks:
      openhab_network:
        ipv4_address: 172.10.5.2
    ports:
      - 3080:80
      - 3443:443
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - /services/openhab/addons:/openhab/addons
      - /services/openhab/config:/openhab/conf
      - /services/openhab/userdata:/openhab/userdata
    environment:
      OPENHAB_HTTP_PORT: "80"
      OPENHAB_HTTPS_PORT: "443"
      EXTRA_JAVA_OPTS: "-Duser.timezone=Africa/Johhanesburg"
    healthcheck:
      test: ["CMD", "curl", "-fk", "https://<domain>:3080"]
      interval: 30s
      timeout: 10s  
      retries: 6
  
  MQTT-broker:
    image: eclipse-mosquitto
    container_name: openhab-mosquitto-broker
    restart: unless-stopped
    networks:
      openhab_network:
        ipv4_address: 172.10.5.3
    ports:
      - 1883:1883
      
networks:
  openhab_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.10.5.0/16
          gateway: 172.10.5.1
