version: "3"
services:
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin-media-server
    user: 1000:1000
    network_mode: "host"
    restart: "unless-stopped"
    healthcheck:
      test: ["CMD", "curl", "-f", "https://media.<domain>"] # Add domain
      interval: 30s
      timeout: 10s
      retries: 6
    volumes:
      - /services/Jellyfin/config:/config
      - jellyfin-cache:/cache # Change cache to directory if necessary
      - /mnt/zfspool/nextcloud/jellyfin/files/Media:/media # Change media directory
      
volumes:
  jellyfin-cache:
    driver: local
