version: '3'
services:
  portainer:
    container_name: portainer
    image: portainer/portainer-ce
    ports:
      - 9000:9000
    restart: unless-stopped
    volumes:
     - /var/run/docker.sock:/var/run/docker.sock
     - /services/portainer/data:/data
    healthcheck:
      test: ["CMD", "curl", "-fk", "http://127.0.0.1:9000"]
      interval: 30s
      timeout: 10s
      retries: 6
